platform :ios, '14.0'

abstract_target 'NovaCrypto' do
    use_frameworks!

    pod 'NovaCrypto', :path => '../..'
    pod 'secp256k1.c', :git => 'https://github.com/novasamatech/secp256k1.c', :tag => '0.1.3'
    pod 'sr25519c', :git => 'https://github.com/novasamatech/sr25519.c', :tag => '0.2.0'
    pod 'ed25519.c', :git => 'https://github.com/novasamatech/ed25519.c', :tag => '0.1.1'
    pod 'blake2.c', :git => 'https://github.com/novasamatech/blake2.c', :tag => '0.1.0'

    target 'NovaCryptoExample'
end

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
            end
        end
    end
end
